#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {model_name}-deployment
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: ${{secrets.OKTETO_NAMESPACE }}
          manifest: manifests/k8s.yaml
          tag: ${{ secrets.DOCKER_USERNAME }}/${{secrets.MODEL_NAME}}:${{github.sha}}
spec:
  selector:
    matchLabels:
      app: {model_name}-server
  replicas: {nodos}
  template:
    metadata:
      labels:
        app: {model_name}-server
    spec:
      containers:
      - name: {model_name}-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/{docker_user}/{model_name}:{github.sha}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {model_name}-service
  name: {model_name}-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {model_name}-server
  type: LoadBalancer
